spring:
  datasource:
    url: jdbc:mysql://waaw-sql.mysql.database.azure.com:3306/waaw_prod?createDatabaseIfNotExist=true&useSSl=true
    username: waaw
    password: W@@WGl0b@l
  mail:
    userName:
    password:

logging:
  config: classpath:log4j2.yml

#########################################
#####    Security Configurations    #####
#########################################
security:
  un-auth-url-patterns: /api/*/unAuth/**, /api/unAuth/**, ${application.websockets.connection-endpoint}/**
  cors-allowed-origins: http://localhost:3000, https://purple-sky-0d8365e10.2.azurestaticapps.net, https://waaw.ca, https://www.waaw.ca
  # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
  jwt-secret: YjE0OTg3YTEyM2YwY2YyNGJjYmZlYTUwNjJkZDQ0YzYxNmUwNjIyMGVkOTIxNTEyODA1M2I3Yjk0NTU5NmIyNjMwZTJiZTlmNjA0YTAyNGY3MzdjOGNlNzQ4OTQzNTAxYmJiM2VlYmRiZGE1YTM5NjhiNGEyNWE1YzA0YTY1MTI=
  jwt-default-token-validity-in-seconds: 1800
  jwt-remember-me-token-validity-in-seconds: 2592000

########################################
#####    Swagger Configurations    #####
########################################
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

##############################
#####    Azure Config    #####
##############################
azure:
  sms:
    end-point: https://waaw-sms.communication.azure.com
    key-credential: kEjXJz/2DRm7taUTcr9mPWcB3dOb+lyki8bvhyzjRA3Syi0bRDBLt6q67CuGW9C49TZT2vPBpUn3g2nFBsyaoA==
  blob:
    payroll-name: prod-payroll
    payroll-key: sp=racwdli&st=2023-03-31T20:08:25Z&se=2200-04-01T04:08:25Z&sv=2021-12-02&sr=c&sig=8aQgD%2FCIcRiWAY8sX2Xo5G3MTTkiNxvftjUFny9BxJs%3D
    attendance-name: prod-attendance
    attendance-key: sp=racwdli&st=2023-03-31T20:06:29Z&se=2200-04-01T04:06:29Z&sv=2021-12-02&sr=c&sig=KwN4eFGos9%2BtAs%2B6cIVBAWD8IPMZuOgLt3DidciVnwA%3D
    holiday-name: prod-holiday
    holiday-key: sp=racwdli&st=2023-03-31T20:07:10Z&se=2200-04-01T04:07:10Z&sv=2021-12-02&sr=c&sig=jpor4zIiHJ1aKs5kg9g7nLB7lGgTexsHAHVCdEeXq90%3D
    pictures-name: prod-pictures
    pictures-key: sp=racwdli&st=2023-03-31T20:08:53Z&se=2200-04-01T04:08:53Z&sv=2021-12-02&sr=c&sig=vQHdvrRuZI3ummqDHBFrm2f%2BKff3P2poGns4%2F1D5754%3D
  send-grid:
    sender-name: WaaW
    sender-email: customer.service@waaw.ca
    api-key: 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

#################################################
#####    Payment properties    #####
#################################################
stripe:
  api-key: sk_test_51IuozbEkZ4NGJcE2m9MpdvSkZbDTFlR2ot3a9vSsQG0QHdwOBKtV9s0pQtKiGN1y3jvMM5ED3dNtVOBxUAMKMxZn00aU9CKJdR

#################################################
#####    Application specific properties    #####
#################################################
application:
  create-dummy-data-on-startup: false
  urls:
    hosted-ui: https://www.waaw.ca
    hosted-server: https://api.waaw.ca
  mail:
    ui-url: ${application.urls.hosted-ui}
